import math
import turtle
wn=turtle.Screen()
wn.bgcolor('lightblue')
fred = turtle.Turtle()
#john = turtle.Turtle()
fred.goto(0,0)
fred.pendown()
#john.goto(0,0)
#john.pendown()
px = float(input("Enter x coordinate: "))
py = float(input("Enter y coordinate: "))
fred.goto(0,px)
fred.goto(px,py)
# fred.penup()
fred.goto(0,0)
#fred.pendown()
pz = math.hypot(px,py)
fred.goto(0,px)
wn.exitonclick()
